FROM arm64v8/python:3.10-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN apt-get update
RUN apt-get -y install gcc python3-dev
RUN pip3 install -r requirements.txt


COPY . .

RUN alembic upgrade head

EXPOSE 8000

CMD [ "python", "main.py" , "--host", "0.0.0.0", "--port", "8000"]